owner/urls.py
from django.urls import path,include
from . import views

app_name="owner"
urlpatterns = [  
    path('', views.index,name='home'),
    path('project', views.projects,name='projects'),
    path('project/<int:id>/', views.projectView, name='project_view'),
    path('project/<int:id>/edit', views.projectEdit, name='project_edit'),
    path('project/<int:id>/delete', views.projectDelete, name='project_delete'),
    path('project/<int:proid>/section/<int:id>', views.sectionView, name='section_view'),
    path('project/<int:proid>/section/<int:id>/edit', views.sectionEdit, name='section_edit'),
    path('project/<int:proid>/section/<int:id>/delete', views.sectionDelete, name='section_delete'),
    path('property/<int:id>/', views.propertyView,name='property_view'),
    path('property/<int:id>/edit', views.propertyEdit,name='property_edit'),
    path('property/<int:id>/delete', views.propertyDelete,name='property_delete'),
    path('', views.projectView, name='customer_view'),     
    ]

    #project/id/edit
    

projects/urls.py
from django.urls import path,include
from . import views


app_name="project"
urlpatterns = [  
    
    path('<int:id>', views.project_profile, name='project_profile'),
    path('availability/<int:id>', views.availability, name='availability'),
    path('booking/project/<int:id>/',views.booking, name='booking'),
    path('', views.project, name='home'),  
    #path('test', views.test),
    
    
]

realEstate/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings 
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('webapp.urls')),
    path('associate/' , include('associate.urls')),
    path('customers/' , include('customers.urls')),
    path('owner/' , include('owner.urls')),
    path('projects/' , include('projects.urls')),
    path('api/customer/' , include('customers.api.urls')),
    path('api/project/' , include('projects.api.urls')),
    path('user/' , include('user.urls'))
    #path('report/' , include('reports.urls'))
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path,include
from . import views

app_name="user"
urlpatterns = [  
    
    path('login', views.login ,name='login'),
   # path('register', views.register ,name='register'),
   # path('forgot-password', views.forgotPassword ,name='forgot'),
    path('logout', views.logout ,name='logout'),
     
    ]

    #project/id/edit
    

owner/models.py
from django.db import models

# Create your models here.

projects/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime, timedelta
from customers.models import Customer

class Project(models.Model):
    CATEGORY = (
             
        ('R', 'Residential'),
        ('C', 'Commercial'),
        
    )
    project_name= models.CharField(max_length=100)
    #project_type=models.ForeignKey(Projecttype, on_delete=models.DO_NOTHING)
    pro_category=models.CharField(max_length=1, choices=CATEGORY)
    project_address= models.TextField(blank=True, null=True)
    pin_code=models.IntegerField(blank=True, null=True)
    description= models.TextField(blank=True, null=True)
    city=models.CharField(max_length=100,blank=True, null=True)
    locality=models.CharField(max_length=100)
    is_active=models.BooleanField(blank=True, null=True)
    geo_code_lat=models.DecimalField(max_digits=10, decimal_places=6,blank=True, null=True)
    geo_code_long=models.DecimalField(max_digits=10, decimal_places=6,blank=True, null=True)
    contact_person_name=models.CharField(max_length=100, blank=True, null=True)
    contact_person_phone=models.BigIntegerField(blank=True, null=True)   
    contact_person_mail=models.EmailField(blank=True, null=True)
    cover_image=models.ImageField(upload_to='images/project/',blank=True, null=True)
    layout= models.FileField(upload_to='files/project/',blank=True, null=True)
    #tags=models.TextField(blank=True, null=True)
    createdAt= models.DateTimeField(auto_now_add=True)
 
    #deactivatedAt= models.DateTimeField(default=timezone.now())   

class Section(models.Model):
    #REduntant possible future use
    TYPE = (             
        ('L', 'Land'),
        ('A', 'Apartment'),
        ('V', 'Villa'),
        ('S', 'Shop'),
        
    )
    name=models.CharField(max_length=50)
    project_ref= models.ForeignKey(Project, on_delete=models.CASCADE)
    section_prefix=models.CharField(max_length=4)
    dimensions=models.CharField(max_length=50)
    area=models.IntegerField()
    cost_per_unit=models.IntegerField()

    class Meta:
        verbose_name = "Section"
        verbose_name_plural = "Sections"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("Section_detail", kwargs={"pk": self.pk})

class PriceRule(models.Model):
    name=models.CharField(max_length=50)
    premium_price=models.IntegerField()   

class Property(models.Model):
    STATUS = (             
        ('V', 'Vacant'),
        ('H', 'Hold'),
        ('B', 'Booked'),
        ('A', 'Alloted'),
        ('R', 'Registered'),        
    )
    serial_no= models.IntegerField()
    status_code=models.CharField(max_length=1, choices=STATUS)
    cust_id=models.ForeignKey(Customer, on_delete=models.CASCADE, blank=True, null=True)
    section_id= models.ForeignKey(Section, on_delete=models.CASCADE)
    price_rule=models.ForeignKey(PriceRule, on_delete=models.CASCADE)
    class Meta:
        verbose_name = "Property"
        verbose_name_plural = "Properties"

    

    def get_absolute_url(self):
        return reverse("Property_detail", kwargs={"pk": self.pk})

class TempBooking(models.Model):
    property_ref=models.ForeignKey(Property, on_delete=models.CASCADE)
    customer_ref=models.ForeignKey(Customer, on_delete=models.CASCADE)
    booking_date=models.DateTimeField()
    booking_revoke_date=models.DateTimeField()
    status= models.BooleanField(default=True)
    
    class Meta:
        verbose_name = ("tempBooking")
        verbose_name_plural = ("tempBookings")


    def get_absolute_url(self):
        return reverse("tempBooking_detail", kwargs={"pk": self.pk})
class Booking(models.Model):
    property_ref=models.ForeignKey(Property, on_delete=models.CASCADE)
    customer_ref=models.ForeignKey(Customer, on_delete=models.CASCADE)
    booking_date=models.DateTimeField(auto_now_add=True)
    booking_revoke_date=models.DateTimeField(auto_now_add=True)
    status= models.BooleanField(default=True)
    
    class Meta:
        verbose_name = ("Booking")
        verbose_name_plural = ("Bookings")


    def get_absolute_url(self):
        return reverse("Booking_detail", kwargs={"pk": self.pk})
class EMI(models.Model):

    property_ref=models.ForeignKey(Property, on_delete=models.CASCADE)
    pay_day=models.DateField(blank=True,auto_now=False, auto_now_add=False)
    opening_balance=models.DecimalField(blank=True,null=True, max_digits=20, decimal_places=2)
    emi=models.DecimalField(blank=True,null=True, max_digits=20, decimal_places=2)
    intrest_paid=models.DecimalField(blank=True,null=True, max_digits=20, decimal_places=2)
    closing_balance=models.DecimalField(blank=True,null=True, max_digits=20, decimal_places=2)
    status= models.BooleanField(default=False)

    class Meta:
        verbose_name = ("emi")
        verbose_name_plural = ("emis") 

    def get_absolute_url(self):
        return reverse("emi_detail", kwargs={"pk": self.pk})
######################################
#Depriciated
#########################################
class NearByPlace(models.Model):
    place_name=models.CharField(max_length=50)
    place_icon=models.CharField(max_length=50)    
    members = models.ManyToManyField(Project, through='Project_nearPlace')
class Project_nearPlace(models.Model):
  #  date_joined = models.DateField()  
    projectref = models.ForeignKey(Project, on_delete=models.CASCADE)
    places = models.ForeignKey(NearByPlace, on_delete=models.CASCADE)
    dist= models.CharField(max_length=50)
    is_allowed=models.BooleanField() 
class Amenity(models.Model):
    amenity_name=models.CharField(max_length=50)
    amenity_icon=models.CharField(max_length=50)    
    members = models.ManyToManyField(Project, through='Project_amenity')
class Project_amenity(models.Model):
  #  date_joined = models.DateField()  
    projectref = models.ForeignKey(Project, on_delete=models.CASCADE)
    amenities = models.ForeignKey(Amenity, on_delete=models.CASCADE)
    is_allowed=models.BooleanField()         
##########################################
class Images(models.Model):
    #imageID
    #entityID
    proref = models.ForeignKey(Project, on_delete=models.CASCADE)
    image_path= models.URLField()
    is_video = models.BooleanField(default=False)
    full_video_path= models.URLField(default='')
    class Meta:
        verbose_name = "Project Image"
        verbose_name_plural = "Project Images"

projects/forms.py
from django import forms
from .models import Project,Section,Property,Booking,TempBooking
class ProjectForm(forms.ModelForm):
    class Meta:
        model= Project
        fields= '__all__'
class SectionForm(forms.ModelForm):
    class Meta:
        model= Section
        fields= '__all__'

class PropertyForm(forms.ModelForm):
    class Meta:
        model= Property
        fields= '__all__'

class BookingForm(forms.ModelForm):
    class Meta:
        model= TempBooking
        fields= ['property_ref',
                'customer_ref',
                'booking_date',
                'booking_revoke_date',
                ]

owner/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib import auth
from projects.models import Project,Section,Property,PriceRule
from projects.forms import ProjectForm,SectionForm,PropertyForm


#side menu options
url="/owner/"
menu=[
    {"id":"1",
    "name":"Dashboard",
    "url": url+"",
    "icon":"fa-tachometer-alt",
    "active":"",
    "sub":[
      
        ], 
    },
    {"id":"2",
    "name":"Projects",
    "url": url+"project",
    "icon":"fa-landmark",
    "active":"",
    "sub":[
        
       
        ],
    },
    {"id":"3",
    "name":"Customers",
    "url": url+"project",
    "icon":"fa-landmark",
    "active":"",
    "sub":[
        
       
        ],
    }
    ]

def sidebarActive(id):
    for menuitem in menu:
        if menuitem['id']==id:
            menuitem['active']="active"
        else:
            menuitem['active']=""  

def index(request):
        sidebarActive("1")
        context= {
            "menu": menu,       
        }       
        return render(request ,'owner/index.html',context) 
        #39xxrqd2yi
def projects(request):
       sidebarActive("2")      
       project_list= Project.objects.all()
       form=ProjectForm(request.POST or None)
       if form.is_valid():
              form.save()
              form=ProjectForm(request.POST or None)

       context={
              "projects": project_list,
              "form":form,
              "menu": menu,
       }       
       return render(request ,'owner/projects.html',context) 
##############################  PROJECTS  ######################################################
def projectView(request,id):
       sidebarActive("2")
       project=Project.objects.get(id=id)
       sections=Section.objects.all().filter(project_ref=id)
       properties=Property.objects.all()
       form=SectionForm(request.POST or None)
       if form.is_valid():
              form.save()
              form=SectionForm(request.POST or None)

       context={
              "project":project,
              "menu": menu,
              "form":form,
              "sections":sections,
              "properties":properties,
       }       
       return render(request ,'owner/projectView.html',context)

def projectEdit(request,id):
       sidebarActive("2")
       project=Project.objects.get(id=id)
       sections=Section.objects.all().filter(project_ref=id)       
       form=ProjectForm(request.POST or None, instance=project)
       if form.is_valid():
              form.save()              

       context={
              "project":project,
              "menu": menu,
              "form":form,
              "sections":sections,
              
       }       
       return render(request ,'owner/projectEdit.html',context)
def projectDelete(request,id):
       project=Project.objects.get(id=id)
       project.delete()
       return redirect('owner:projects')
##################################### SECTIONS #####################################################
def sectionView(request,proid,id):
       sidebarActive("2")
       project=Project.objects.get(id=proid)
       sections=Section.objects.get(id=id)
       properties=Property.objects.all().filter(section_id=id)
       price_rules=PriceRule.objects.all()
       form=PropertyForm(request.POST or None)
       if form.is_valid():
              form.save()
              form=PropertyForm(request.POST or None)
       context={
              "project":project,
              "menu": menu,
              "form":form,
              "section":sections,
              "properties":properties,
              "price_rules":price_rules,
       }       
       return render(request ,'owner/sectionView.html',context)  
      
def sectionEdit(request,id,proid):
       sidebarActive("2")
       section=Section.objects.get(id=id)             
       form=SectionForm(request.POST or None, instance=section)
       if form.is_valid():
              form.save()              

       context={
              "section":section,
              "menu": menu,
              "form":form
       }       
       return render(request ,'owner/sectionEdit.html',context)
def sectionDelete(request,id,proid):
       section=Section.objects.get(id=id)
       section.delete()
       return redirect('owner:projects')
       
############################## PROPERTY #######################################################
def propertyView(request,id):
       sidebarActive("2")       
       properties=Property.objects.get(id=id)    
       context={
              "property":properties,
              "menu": menu,                  
       }       
       return render(request ,'owner/propertyView.html',context)  
      
def propertyEdit(request,id):
       sidebarActive("2")
       print(request.POST)
       prop=Property.objects.get(id=id)
       #proid=Property.section_id.project_ref.id
       #prop.section_id=Section.objects.all().filter(project_ref=proid)   
       price_rules=PriceRule.objects.all()          
       form=PropertyForm(request.POST or None, instance=prop)        
       if form.is_valid():
              form.save()              

       context={
              "property":prop,
              "menu": menu,
              "form":form,
              "price_rules":price_rules,
       }       
       return render(request ,'owner/propertyEdit.html',context)
def propertyDelete(request,id):
       properties=Property.objects.get(id=id)
       properties.delete()
       return redirect('owner:projects')
       
 

     

projects/api/views.py
from rest_framework import viewsets,status,generics
from rest_framework.views import APIView
from rest_framework.response import Response
from customers.api.serializers import CustomerSerializer
from customers.models import Customer
from projects.models import Property,PriceRule
from projects.api.serializers import PropertySerializer 



class PropertyAPIView(APIView):
    def get(self, request,section_id):
        queryset= Property.objects.all().filter(section_id=section_id)
        serializer_context = {
            'request': request,
        }
     
        serializer= PropertySerializer(instance=queryset,context=serializer_context, many=True)
        return Response(serializer.data, headers={'Access-Control-Allow-Origin': '*'})

class CustomerRudView(generics.RetrieveUpdateDestroyAPIView):
  lookup_field=  'id'
  serializer_class= CustomerSerializer
  def get_queryset(self):    
    queryset = Customer.objects.all() # TODO
    return queryset
  #def get_object(self):
  #,'section_id','price_rule'
    #contact_no=self.kwargs.get('contact_no')
    #return Customer.objects.get(contact_no=contact_no)

class CustomerCreateApiView(generics.CreateAPIView):
    lookup_field= 'pk'
    serializer_class= CustomerSerializer    
    def get_queryset(self):        
        queryset= Customer.objects.all()
        return queryset

owner/templates/owner/blank.html
{% extends "base.html" %}
{% block title %}
{{project.project_name}} Project
{% endblock title %}
<!-- heading  -->
{% block heading %}
{{project.project_name}} Project
{% endblock %}


<!-- desktop menu -->
{% block desk-sidebar%}
{% include 'sidebar.html' %}
{% endblock %}

<!-- Main Conent -->
{% block content %}
<div class="row m-t-25">
    <div class="col-lg-12">
        sdf
    </div>

</div>
{% endblock %}


{% load static %}

owner/templates/owner/index.html
{% extends "base.html" %}
{% block title %}
Dashboard
{% endblock title %}
<!-- heading  -->
{% block heading %}
Dashboard
{% endblock %}


<!-- desktop menu -->
{% block desk-sidebar%}
{% include 'sidebar.html' %}
{% endblock %}

<!-- Main Conent -->
{% block content %}

{% endblock %}


{% load static %}

owner/templates/owner/projectView.html
{% extends "base.html" %}
{% block title %}
{{project.project_name}} Project
{% endblock title %}
<!-- heading  -->
{% block heading %}
{{project.project_name}} Project
{% endblock %}


<!-- desktop menu -->
{% block desk-sidebar%}
{% include 'sidebar.html' %}
{% endblock %}

<!-- Main Conent -->
{% block content %}
<div class="row ">

  <div class="col-12">
    <div class="card">
      <div class="card-header" style="background-image: url('{{project.cover_image}}');
                    background-position: center;
                    background-size: cover;
                    height: 300px;
            ">
        <div class="bg-dark">

        </div>
      </div>
      <div class="card-body">
        <table class="table ml-1 mr-1">
          <tbody>
            <tr>
              <th scope="row">Project ID</th>
              <td></td>
              <td>{{project.id}}</td>
            </tr>
            <tr>
              <th scope="row">Project Name</th>
              <td></td>
              <td>{{project.project_name}}</td>
            </tr>
            <tr class="">

              <th scope="row">Category</th>
              <td></td>
              <td>
                {% if project.pro_category == "R"%}
                <span class="text-primary">Residential</span>
                {% elif project.pro_category == "C"%}
                <span class="badge badge-danger">Commercial</span>
                {% else%}
                <span class="badge badge-warning">Others</span>
                {% endif %}

              </td>
            </tr>
            <tr>
              <th scope="row">Project Locality</th>
              <td></td>
              <td>{{project.locality}}</td>
            </tr>
            <tr>
              <th scope="row">Project Address</th>
              <td></td>
              <td>{{project.project_address}},{{project.city}}-{{project.pin_code}}</td>
            </tr>
            <tr>
              <th scope="row">Project Status</th>
              <td></td>
              <td>
                {% if project.is_active %}
                <span class="badge badge-success">Active</span>
                {% else%}
                <span class="badge badge-danger">Not active</span>
                {% endif %}
              </td>
            </tr>

            <tr>
              <th scope="row">Contact Person Name</th>
              <td></td>
              <td>{{project.contact_person_name}}</td>
            </tr>
            <tr>
              <th scope="row">Contact Person Phone</th>
              <td></td>
              <td>{{project.contact_person_phone}}</td>
            </tr>
            <tr>
              <th scope="row">Contact Person Email</th>
              <td></td>
              <td>{{project.contact_person_mail}}</td>
            </tr>
            <tr>
              <th scope="row">Project Description</th>
              <td></td>
              <td>{{project.description}}</td>
            </tr>
            <tr>
              <th scope="row">GPS Geocode</th>
              <td></td>
              <td>lat:{{project.geo_code_lat}}, long:{{project.geo_code_long}}</td>
            </tr>

          </tbody>
        </table>
      </div>

      <div class="p-3 align-self-center ">
        <button type="button" class="btn btn-sm btn-primary m-1" data-toggle="modal" data-target="#exampleModal">
          <i class="fas fa-plus-circle"></i>
          Add Sections
        </button>
        <a href="{% url 'owner:project_edit' id=project.id %} " class="btn btn-warning btn-sm float-left m-1">
          <i class="far fa-edit"></i>
          Edit Project</a>
        <button class="btn btn-sm m-1 float-right btn-danger" onclick="del()">
          <i class="far fa-trash-alt"></i>
          Delete
        </button>


        <script>
          function del() {
            swal({
              title: "Are you sure?",
              text: "You wont be able to revert this!",
              type: "warning",
              showCancelButton: true,
              confirmButtonColor: "#00C851",
              cancelButtonColor: "#d33",
              confirmButtonText: "Yes, delete it!",
              confirmButtonClass: "btn btn-success"
            }).then((result) => {
              if (result.value) {
                Swal.fire(
                  'Deleted!',
                  'Your file has been deleted.',
                  'success'
                )
                window.location = "{% url 'owner:project_delete' id=project.id %}";
              }
            })
              ;

          }
        </script>

      </div>

      <hr>
      <div class="d-flex flex-row justify-content-center mt-2">
        <div>
          <nav>
            <div class="nav nav-tabs" id="nav-tab" role="tablist">
              {% for section in sections %}
              <a class="nav-item nav-link " id="nav-{{section.name}}-tab" data-toggle="tab"
                href="#{{section.section_prefix}}" role="tab" aria-controls="nav-home"
                aria-selected="true">{{section.name}}</a>
              {% endfor %}

            </div>
          </nav>
        </div>


      </div>

      <div class="tab-content" id="nav-tabContent">
        {% for section in sections %}
        <div class="tab-pane fade show " id="{{section.section_prefix}}" role="tabpanel"
          aria-labelledby="nav-{{section.section_prefix}}-tab">

          <div class="d-flex flex-row justify-content-center mt-3 mb-3">
            {% url 'owner:section_view' proid=project.id id=section.id as url_s %}
            <a class="btn btn-sm btn-outline-primary" href="{{url_s}}">
              <i class="far fa-eye"></i>
              View Section Details</a>
          </div>

          <div class="table-responsive ">
            <table class=" myTable table table-striped ">
              <thead>
                <tr>
                  <th>Serial No.</th>
                  <th>Price Rule</th>
                  <th>Cost per Unit</th>
                  <th>Status</th>
                  <th>Customer Name</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                {% load mathfilters %}
                {% for property in properties %}
                
                {% if property.section_id.id == section.id %}

                <tr>
                  <td>{{section.section_prefix}}-{{property.serial_no}} </td>
                  <td>{{property.price_rule.name}}</td>
                  <td>

                    {% with cost=section.cost_per_unit factor=property.price_rule.premium_price|add:100|div:100 %}
                    &#8377; {{cost|mul:factor}}</td>
                  {% endwith %}
                  <td>
                    {% if property.status_code == "V"  %}
                    <span class="badge  badge-pill badge-success">Vacant</span>
                    {% elif property.status_code == "H" %}
                    <span class="badge badge-pill badge-warning">Hold</span>
                    {% elif property.status_code == "B" %}
                    <span class="badge badge-pill badge-danger">Booked</span>
                    {% elif property.status_code == "A" %}
                    <span class="badge badge-pill badge-primary">Alloted</span>
                    {% else  %}
                    <span class="badge badge-pill badge-secondary">Registered</span>

                    {% endif %}
                    <!--  -->
                  </td>
                  <td>
                    
                    {% if property.cust_id.name %}
                    <a href="{% url 'owner:customer_view' %}">
                        {{property.cust_id.name}}</a>
                        {% else %}
                        <span class="text-danger">NONE</span>
                    {% endif %}
                      
                    </td>
                  <td>
                    <a class="btn btn-sm  btn-default"
                    href="{% url 'owner:property_view' id=property.id %} "
                    >
                      <i class="far fa-eye"></i>
                    </a>
                    <a class="btn btn-sm  btn-warning"
                    href="{% url 'owner:property_edit' id=property.id %} "
                    >
                      <i class="far fa-edit"></i>
                    </a>
                    <a class="btn btn-sm  btn-danger"
                    href="{% url 'owner:property_delete' id=property.id %}" >
                    <i class="far fa-trash-alt"></i>              
                    </a>
                    
                  
                  </td>

                </tr>
                {% endif %}
                {% endfor %}

              </tbody>
            </table>
            <script>
              $(document).ready(function () {
                $('.myTable').DataTable();
              });
            </script>


          </div>




        </div>
        {% endfor %}
      </div>


      <!--     <div class="d-flex flex-row justify-content-center" style="margin-top: 40%;">
        <div></div>
        <div class="p-3 align-self-end ">
          <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
            Add Projects
          </button>
        </div>
      </div> -->



    </div>
  </div>


</div>
{% endblock %}

{% block modal %}
<!-- Modals Start -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add Sections</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="" method="post">
          {% csrf_token %}
          {% load crispy_forms_tags %}
          <!--  {{form|crispy}} -->
          <div class="form-row">
            <div class="form-group col-auto mb-0">
              {{ form.name|as_crispy_field }}
              <span class="form-text text-muted" style="font-size: 10pt;
                font-weight: 500;
                text-transform: capitalize;
                ">
                Example: Section A
              </span>
            </div>
            <input type="hidden" name="project_ref" value="{{project.id}}">
          </div>
          <div class="form-row">
            <div class="form-group col-auto mb-0">
              {{ form.dimensions|as_crispy_field }}
              <span class="form-text text-muted" style="font-size: 10pt;
                font-weight: 500;
                text-transform: capitalize;
                ">
                Example: 45 x 30 In feets
              </span>
            </div>
            <div class="form-group col-auto mb-0">
              {{ form.section_prefix|as_crispy_field }}
              <span class="form-text text-muted" style="font-size: 10pt;
            font-weight: 500;
            text-transform: capitalize;
            ">
                Example: A in A-1
              </span>
            </div>

          </div>
          <div class="form-row">
            <div class="form-group col-auto mb-0">
              {{ form.area|as_crispy_field }}
              <span class="form-text text-muted" style="font-size: 10pt;
                font-weight: 500;
                text-transform: capitalize;
                ">
                Example: 500 In square feets
              </span>
            </div>
            <div class="form-group col-auto mb-0">
              {{ form.cost_per_unit|as_crispy_field }}
              <span class="form-text text-muted" style="font-size: 10pt;
            font-weight: 500;
            text-transform: capitalize;
            ">
                Example: &#8377; 600 per square feets
              </span>
            </div>


          </div>


      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Save</button>
      </div>

      </form>
    </div>

  </div>
</div>
{% endblock %}
<!-- Button trigger modal -->

owner/templates/owner/sectionEdit.html
{% extends "base.html" %}
{% block title %}
{{section.project_ref.project_name}} Section EDIT
{% endblock title %}
<!-- heading  -->
{% block heading %}
{{section.project_ref.project_name}} {{section.name}} EDIT
{% endblock %}


<!-- desktop menu -->
{% block desk-sidebar%}
{% include 'sidebar.html' %}
{% endblock %}

<!-- Main Conent -->
{% block content %}
<div class="col-12">
    <div class="card">
        <div class="card-header" style="background-image: url('{{section.project_ref.cover_image}}');
                      background-position: center;
                      background-size: cover;
                      height: 300px;
              ">

        </div>




        <div class="d-flex justify-content-center ">

            <form action="" method="post">
                {% csrf_token %}
                {% load crispy_forms_tags %}
                <table class="table">
                       <thead>
                           <tr>
                               <td>Name</td>
                               <td>Value</td>


                            </tr>
                       </thead>
                        <tbody>
                                {{ form.as_table }} 
                        </tbody>
                </table>
                <!-- {{form|crispy}} -->

                <button type="submit" class="btn btn-primary btn-sm"
                
                onclick='swal({ title:"Project Updated!",timer: 2000, text: "You clicked the button!", type: "success", buttonsStyling: false, confirmButtonClass: "btn btn-success"})'
                >Update</button>
            </form>

            <!-- markup -->

<!-- for more actions that you can use onclick, please check out assets/demo/js/demo.js -->
        </div>

    </div>
</div>
</div>

{% endblock %}


{% load static %}