customers/urls.py
from django.urls import path,include
from . import views

app_name="customers"
urlpatterns = [    
    path('login', views.login, name='login'),
    path('login/loader', views.loader, name='loader'),    
    path('register', views.register,name='register'),
    path('home/<int:id>', views.home,name='home'),    
    #path('', views.home,name='home'),
    
        
    
    
]

realEstate/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings 
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('webapp.urls')),
    path('associate/' , include('associate.urls')),
    path('customers/' , include('customers.urls')),
    path('owner/' , include('owner.urls')),
    path('projects/' , include('projects.urls')),
    path('api/customer/' , include('customers.api.urls')),
    path('api/project/' , include('projects.api.urls')),
    path('user/' , include('user.urls'))
    #path('report/' , include('reports.urls'))
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path,include
from . import views

app_name="user"
urlpatterns = [  
    
    path('login', views.login ,name='login'),
   # path('register', views.register ,name='register'),
   # path('forgot-password', views.forgotPassword ,name='forgot'),
    path('logout', views.logout ,name='logout'),
     
    ]

    #project/id/edit
    

user/models.py
from django.db import models

# Create your models here.

user/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User,Group
from django.contrib import auth,messages
from config.models import Company
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm


company_details=Company.objects.all()

def index(request):
  context={
           
           "details":company_details,                                 
    }
  return render(request ,'user/index.html', context)
def login(request):
    context={
           
           "details":company_details,                                 
    }
    if request.method=='POST':
        user= auth.authenticate(username=request.POST['username'],password=request.POST['password'])
        if user is not None:
            auth.login(request,user)
            if  user.groups.filter(name='Associate').exists():
              return redirect('associate:home')
            elif user.groups.filter(name='Owner').exists():
              return redirect('owner:home')
            else:
              print(user.groups.name)
              return redirect('webapp:home')
           # return redirect('associate:home')
        else:
            context={
           
           "details":company_details,
           'error':' Wrong ID or password '                                 
            }
            return render(request ,'user/login.html', context) 
    else:
        return render(request ,'user/login.html', context)


def register(request):
  context={
           
           "details":company_details,                                 
    }
  if request.method=='POST':
        try:
            if request.POST['password']==request.POST['cnf-password']:
                user = User.objects.get(username=request.POST['username'])
                context1={
           
                  "details":company_details,
                  'error':'Oops! This email is already registered'                                 
                    }
                return render(request ,'user/register.html', context1) 
        except :
           
            user= User.objects.create_user(request.POST['username'],password=request.POST['password'], email=request.POST['username'])
            group = Group.objects.get(name='Associate')
            user.groups.add(group)
            auth.login(request,user)
            if  user.groups.filter(name='Associate').exists():
              return redirect('associate:home')
            else:
              print(user.groups.name)
              return redirect('webapp:home')
  else:
        return render(request ,'user/register.html', context)   
  return render(request ,'user/register.html', context)
  
def forgotPassword(request):
  context={
           
           "details":company_details,                                 
    }
  return render(request ,'user/index.html', context)
def logout(request):
    if request.method=='POST':
        auth.logout(request)
        return redirect('webapp:home')

def passwordChange(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('user:')
        else:
            messages.error(request, 'Passwords do not match')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'user/changePassword.html', {
        'form': form
    })
    

user/templates/user/changePassword.html
{% extends "base.html" %}
{% block title %}
Change Password
{% endblock title %}
<!-- heading  -->
{% block heading %}
Change Password
{% endblock %}

<!-- desktop menu -->
{% block desk-sidebar%}
{% include 'sidebar.html' %}
{% endblock %}


<!-- Main Conent -->
{% block content %}
<div class="row ">
    <div class="col-lg-12">
        <form action="" method="post">
            {% csrf_token %}

            {% load crispy_forms_tags %}
            {{form|crispy }}
            <button class="btn  btn-success">Submit</button>
        </form>
    </div>

</div>
{% endblock %}


{% load static %}

user/templates/user/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>
        saasd
    </h1>
</body>
</html>

user/templates/user/login.html
{% extends "home-base.html" %}
{% block title %}
Customer Login 
{% endblock title %}
{% load static %}

{% block body %}

{% load static %}
{% if company.use_url %}
<div class="page-header header-filter" data-parallax="false" style="height: 900px;;
background-image: url('{{company.bg_url}}')">
{% else %}
<div class="page-header header-filter" data-parallax="true" style="height: 800px;
background-image: url('{% get_media_prefix %}{{company.bg_upload}}')">
{% endif %}
    <div class="container">
      <div class="row">
        <div class="col-md-8 ml-auto mr-auto mb-5">
          <div class="brand text-center">
                <h1>Welcome to {{company.name}} </h1>
             
          </div>

          
        </div>
      </div>

        <div class="row">
          <div class="col-lg-4 col-md-6 ml-auto mr-auto">
            <div class="card card-login">
                <div class="card-header card-header-rose text-center">
                  <h4 class="card-title">Associate Login</h4>
                  <br>
                </div>    
          
                {% if error %}
                <div class="alert alert-danger" role="alert">
                       {{error}}
                   </div> 
                {%else %}
                <br>
                <br>
                {% endif %}
                <form class="text-center" action=" {% url 'user:login'  %} " method="post">
                        {% csrf_token %}
                        {% load crispy_forms_tags %}
          
                        {% load widget_tweaks %}
                        <div class="input-group">
                            <div class="input-group-prepend">
                              <span class="input-group-text">
                                <i class="material-icons">face</i>
                              </span>
                            </div>
                            <input type="text" class="form-control" name="username" placeholder="Username....">
                        </div>
                        <div class="input-group">
                            <div class="input-group-prepend">
                              <span class="input-group-text">
                                <i class="material-icons">lock_outline</i>
                              </span>
                            </div>
                            <input type="password" class="form-control" name="password" placeholder="Password...">
                          </div>
             
          
                       
                    <button class="btn btn-primary">Login</button>
                </form>
            <!--    
                <div class="d-flex justify-content-between mt-3">
                  <div class="p-2">
                    <a href="" class=" text-primary">Register Here</a>
                  </div>
                  <div class="p-2"></div>

                  <div class="p-2">
                    <a href="" class=" text-primary">Forgot Password</a>
                  </div>
                </div> -->
                <br>
                
            </div>
          </div>
        </div>
      </div>
  </div>

  {% endblock %}

user/templates/user/register.html
{% extends "home-base.html" %}
{% block title %}
Customer Login 
{% endblock title %}
{% load static %}

{% block body %}

{% load static %}
{% if company.use_url %}
<div class="page-header header-filter" data-parallax="false" style="height: 900px;;
background-image: url('{{company.bg_url}}')">
{% else %}
<div class="page-header header-filter" data-parallax="true" style="height: 800px;
background-image: url('{% get_media_prefix %}{{company.bg_upload}}')">
{% endif %}
    <div class="container">
      <div class="row">
        <div class="col-md-8 ml-auto mr-auto mb-5">
          <div class="brand text-center">
                <h1>Welcome to {{company.name}} </h1>
             
          </div>

          
        </div>
      </div>

        <div class="row">
          <div class="col-lg-4 col-md-6 ml-auto mr-auto">
            <div class="card card-login">
                <div class="card-header card-header-rose text-center">
                  <h4 class="card-title">Associate Register</h4>
                  <br>
                </div>    
          
                {% if error %}
                <div class="alert alert-danger" role="alert">
                       {{error}}
                   </div> 
                {%else %}
                <br>
                <br>
                {% endif %}
                <form class="text-center" action=" {% url 'user:register'  %} " method="post">
                        {% csrf_token %}
                        {% load crispy_forms_tags %}
          
                        {% load widget_tweaks %}
                        <div class="input-group">
                            <div class="input-group-prepend">
                              <span class="input-group-text">
                                <i class="material-icons">email</i>
                              </span>
                            </div>
                            <input type="text" class="form-control" name="username" placeholder="Email">
                        </div>
                       
                        <div class="input-group">
                            <div class="input-group-prepend">
                              <span class="input-group-text">
                                <i class="material-icons">lock_outline</i>
                              </span>
                            </div>
                            <input type="password" class="form-control" name="password" placeholder="Password...">
                          </div>
                          <div class="input-group">
                            <div class="input-group-prepend">
                              <span class="input-group-text">
                                <i class="material-icons">lock_outline</i>
                              </span>
                            </div>
                            <input type="password" class="form-control" name="cnf-password" placeholder="Confirm Password">
                          </div>
             
          
                       
                    <button class="btn btn-primary">Submit</button>
                </form>
         
                <br>
                
            </div>
          </div>
        </div>
      </div>
  </div>

  {% endblock %}