associate/urls.py
from django.urls import path,include
from . import views

app_name="associate"
urlpatterns = [  
    path('', views.index,name='home'),
   # path('register', views.register, name='register'),
    path('project', views.projects,name='projects'),
    path('project/<int:id>/', views.projectView, name='project_view'),
    path('project/<int:proid>/section/<int:id>', views.sectionView, name='section_view'), 
    path('property/<int:id>/', views.propertyView,name='property_view'),  
    path('customers', views.customerListView, name='customers'),
    path('customers/<int:id>/', views.customerView, name='customer_view'),
    path('rewards', views.rewardView, name='rewards'),
    path('upline', views.uplineView, name='upline'), 
    path('downlines', views.downlines, name='downlines'),
    path('downlines/<int:id>', views.downlineView, name='downline_view'),   
    path('buisness-summary', views.buisnessSummary, name='buisness_summary'),
    path('team-buisness', views.teamBuisness, name='team_buisness'),
    path('leader-rewards', views.leaderRewards, name='leader_rewards'),
    path('my-earnings', views.myEarnings, name='my_earnings'),
    path('earnings-forcast', views.earningForcast, name='earning_forcast'),
    path('passbook', views.passbook, name='passbook'),
    path('profile', views.myProfile, name='profile'),
    path('profile/edit', views.profileEdit, name='profile_edit'), 
    path('changepwd', views.changePwd, name='changepwd'),              
    ]

    #project/id/edit
    

customers/urls.py
from django.urls import path,include
from . import views

app_name="customers"
urlpatterns = [    
    path('login', views.login, name='login'),
    path('login/loader', views.loader, name='loader'),    
    path('register', views.register,name='register'),
    path('home/<int:id>', views.home,name='home'),    
    #path('', views.home,name='home'),
    
        
    
    
]

projects/urls.py
from django.urls import path,include
from . import views


app_name="project"
urlpatterns = [  
    
    path('<int:id>', views.project_profile, name='project_profile'),
    path('availability/<int:id>', views.availability, name='availability'),
    path('booking/project/<int:id>/',views.booking, name='booking'),
    path('', views.project, name='home'),  
    #path('test', views.test),
    
    
]

user/urls.py
from django.urls import path,include
from . import views

app_name="user"
urlpatterns = [  
    
    path('login', views.login ,name='login'),
   # path('register', views.register ,name='register'),
   # path('forgot-password', views.forgotPassword ,name='forgot'),
    path('logout', views.logout ,name='logout'),
     
    ]

    #project/id/edit
    

associate/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class Associate(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE,blank=True,null=True)
    name= models.CharField(max_length=100)
    upline= models.ForeignKey('self', on_delete=models.CASCADE)
    country_code=models.CharField(max_length=50,blank=True,null=True)   
    contact_no=models.BigIntegerField(unique=True)
    alternate_no=models.BigIntegerField()
    email= models.EmailField(unique=True)
    address=models.CharField(max_length=100)
    photo=models.ImageField(upload_to='images/associate/',blank=True, null=True)
    status=models.BooleanField(default=False)
    createdAt= models.DateTimeField(auto_now_add=True)

# Create your models here.

associate/forms.py
from django import forms
from .models import Associate
class AssociateForm(forms.ModelForm):
    class Meta:
        model= Associate
        fields= ['user',
        'name',
        'upline',
        'contact_no',
        'alternate_no',
        'email',
        'address',
        'photo'
        ]
class UpdateForm(forms.ModelForm):
    class Meta:
        model= Associate
        fields= [
        'name',
        
        'contact_no',
        'alternate_no',
        'email',
        'address',
        'photo'
        ]

customers/forms.py
from django import forms
from .models import Customer
class CustomerForm(forms.ModelForm):
    class Meta:
        model= Customer
        fields= [
        'name',
        'associate_ref',
        'contact_no',
        'country_code',
        'alternate_no',
        'email',
        'address'
        ]

associate/views.py
from django.shortcuts import render, redirect,reverse
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib import auth,messages
from django.utils import timezone
from projects.models import Project,Section,Property,PriceRule,EMI
from projects.forms import ProjectForm,SectionForm,PropertyForm
from .models import Associate
from .forms import AssociateForm,UpdateForm
from customers.models import Customer,Transaction
from reports.models import MonthlySales,Sale,PayoutLifetime,PayoutMonthly,PayoutRule
from django.db.models import Sum,Count,Max
from user.views import passwordChange
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from .tasks import generate_monthly_sales_report,update_lifetime_payout
#side menu options
url="/associate/"


menu=[
    {"id":"1",
    "name":"Dashboard",
    "url": url+"",
    "icon":"fa-tachometer-alt",
    "active":"",
    "sub":[
      
        ], 
    },
    {"id":"2",
    "name":"Projects",
    "url": url+"project",
    "icon":"fa-landmark",
    "active":"",
    "sub":[
        
       
        ],
    },
    {"id":"3",
    "name":"My Business",
    "url": url+"project",
    "icon":"fa-briefcase",
    "active":"",
    "sub":[
        {"name": "View my Clients",
        "url": url+"customers", },
         {"name": "My Buisness Summary",
        "url": url+"buisness-summary", },
        {"name": "Team Buisness",
        "url": url+"team-buisness", },
        {"name": "Leader Rewards",
        "url": url+"leader-rewards", },        
         {"name": "My Buisness Rewards",
        "url": url+"rewards", },
       
        ],
    },
       {"id":"4",
    "name":"My team",
    "url": url+"project",
    "icon":"fa-users",
    "active":"",
    "sub":[
        
         {"name": "My Uplines",
        "url": url+"upline", },
        
         {"name": "My Downlines",
        "url": url+"downlines", },
        {"name": "Add New Downline",
        "url": url+"downlines", },
       
        ],
    },
       {"id":"5",
    "name":"Finance",
    "url": url+"project",
    "icon":"fa-rupee-sign",
    "active":"",
    "sub":[
        
         {"name": "My Earnings",
        "url": url+"my-earnings", },
           {"name": "Earning Forcast",
        "url": url+"earnings-forcast", },
        {"name": "Passbook",
        "url": url+"passbook", },
       
        ],
    },
    ]
#assoicate_id=user
def sidebarActive(id):
    for menuitem in menu:
        if menuitem['id']==id:
            menuitem['active']="active"
        else:
            menuitem['active']=""  
def register(request):
       form=AssociateForm(request.POST,request.FILES or None)
       if form.is_valid():
              form.save()
              messages.success(request, 'You have successfully registered!')
              return redirect(reverse('associate:home'))
       error=False
       try:     
              associate=Associate.objects.get(user=current_user)
              error=True
       except:
              error=True
       context={
              "form":form,
              "error":error,
       }
       return render(request ,'associate/register.html',context)    
 
def index(request):
        sidebarActive("1")
        current_user = request.user
        try:     
             associate=Associate.objects.values('name','photo').get(user=current_user)
        except:
              return redirect('user:login') 
        context= {
            "menu": menu,
            "associate":associate,
            "current_user":current_user,       
        }       
        return render(request ,'associate/index.html',context) 
        #39xxrqd2yi
def projects(request):
       sidebarActive("2")      
       current_user = request.user     
       try:     
              associate=Associate.objects.values('name','photo').get(user=current_user)
       except:
              return redirect('associate:register')
       project_list= Project.objects.only('id','cover_image', 'project_name', 'locality','city')
       form=ProjectForm(request.POST or None)
       if form.is_valid():
              form.save()
              form=ProjectForm(request.POST or None)

       context={
              "projects": project_list,
              "form":form,
              "menu": menu,
              "associate":associate,
       }       
       return render(request ,'associate/projects.html',context) 
##############################  PROJECTS  ######################################################
def projectView(request,id):
       sidebarActive("2")
       current_user = request.user     
       try:     
              associate=Associate.objects.values('name','photo').get(user=current_user)
       except:
              return redirect('associate:register')
       project=Project.objects.values('id',
       'project_name',
       'cover_image',
       'pro_category',
       'locality',
       'project_address',
       'city',
       'pin_code',
       'description',
       'is_active',).get(id=id)
       sections=Section.objects.all().filter(project_ref=id)
       properties=Property.objects.select_related('price_rule').all().order_by('serial_no')
       form=SectionForm(request.POST or None)
       if form.is_valid():
              form.save()
              form=SectionForm(request.POST or None)

       context={
              "project":project,
              "menu": menu,
              "associate":associate,
              "form":form,
              "sections":sections,
              "properties":properties,
       }       
       return render(request ,'associate/projectView.html',context)


##################################### SECTIONS #####################################################
def sectionView(request,proid,id):
       sidebarActive("2")
       current_user = request.user     
       try:     
              associate=Associate.objects.get(user=current_user)
       except:
              return redirect('associate:register')
       project=Project.objects.get(id=proid)
       sections=Section.objects.get(id=id)
       properties=Property.objects.select_related('price_rule').filter(section_id=id).order_by('serial_no')
       price_rules=PriceRule.objects.all()
       form=PropertyForm(request.POST or None)
       if form.is_valid():
              form.save()
              form=PropertyForm(request.POST or None)
       context={
              "project":project,
              "menu": menu,
              "associate":associate,
              "form":form,
              "section":sections,
              "properties":properties,
              "price_rules":price_rules,
       }       
       return render(request ,'associate/sectionView.html',context) 
      

       
############################## PROPERTY #######################################################
def propertyView(request,id):
       sidebarActive("2")     
       current_user = request.user     
       try:     
              associate=Associate.objects.get(user=current_user)
       except:
              return redirect('associate:register')  
       properties=Property.objects.select_related('price_rule','section_id').get(id=id)
       paid_emi=EMI.objects.all().filter(property_ref=id).filter(status=True).aggregate(Count('emi'))
       pending_emi=EMI.objects.all().filter(property_ref=id).filter(status=False).aggregate(Count('emi'))    
       context={
              "property":properties,
              "menu": menu,
              "associate":associate,  
              "paid_emi":paid_emi,
              "pending_emi":pending_emi,                
       }       
       return render(request ,'associate/propertyView.html',context)
       
############################## CUSTOMERS #######################################################
def customerListView(request):
       sidebarActive("3")
       current_user = request.user     
       try:     
              associate=Associate.objects.get(user=current_user)
       except:
              return redirect('associate:register')       
       customers=Customer.objects.all()
       properties=Property.objects.all() 
       context={
              "customers":customers,
              "menu": menu,
              "associate":associate,
              "properties":properties
                              
       }       
       return render(request ,'associate/customers.html',context)
def customerView(request,id):
       sidebarActive("3")
       current_user = request.user     
       try:     
              associate=Associate.objects.get(user=current_user)
       except:
              return redirect('associate:register')       
       customer=Customer.objects.get(id=id)
       properties=Property.objects.all().filter(cust_id=id)
       emi=EMI.objects.all().filter(property_ref__cust_id=id)
       amount=Transaction.objects.all().filter(customer_ref=id).aggregate(Sum('amount'))
       tx=Transaction.objects.all().filter(customer_ref=id)
       paid_emi=EMI.objects.all().filter(property_ref__cust_id=id).filter(status=True).aggregate(Count('emi'))
       pending_emi=EMI.objects.all().filter(property_ref__cust_id=id).filter(status=False).aggregate(Count('emi'))
       context={
              "customer":customer,
              "menu": menu,                  
             "associate":associate,
             "properties":properties,
             "amount":amount,
             "emi":emi,
             "pending_emi":pending_emi,
             "paid_emi":paid_emi,
             "tx":tx,
              
       }
       return render(request ,'associate/customerView.html',context)

def rewardView(request):
       sidebarActive("3")
       current_user = request.user     
       try:     
              associate=Associate.objects.get(user=current_user)
       except:
              return redirect('associate:register')
       context={
              
              "menu": menu,                  
             "associate":associate,
       }

customers/api/views.py
from rest_framework import viewsets,status,generics
from rest_framework.views import APIView
from rest_framework.response import Response
from customers.api.serializers import CustomerSerializer
from customers.models import Customer

class CustomerView(APIView):
    def get(self, request,contact_no):
        queryset= Customer.objects.all().filter(contact_no=contact_no)
        serializer_context = {
            'request': request,
        }
        serializer= CustomerSerializer(instance=queryset,context=serializer_context, many=True)
        content = {
            'message': 'Hello, World!',            
        }
        return Response(serializer.data, headers={'Access-Control-Allow-Origin': '*'})

class CustomerRudView(generics.RetrieveUpdateDestroyAPIView):
  lookup_field=  'id'
  serializer_class= CustomerSerializer
  def get_queryset(self):    
    queryset = Customer.objects.all() # TODO
    return queryset
  #def get_object(self):
    #contact_no=self.kwargs.get('contact_no')
    #return Customer.objects.get(contact_no=contact_no)

class CustomerCreateApiView(generics.CreateAPIView):
    lookup_field= 'pk'
    serializer_class= CustomerSerializer    
    def get_queryset(self):        
        queryset= Customer.objects.all()
        return queryset

customers/views.py
from django.shortcuts import render,redirect
from customers.forms import CustomerForm
from .models import Customer,Transaction
from config.models import Company
from associate.models import Associate
from django.urls import reverse
from projects.models import Booking,TempBooking, EMI


# Create your views here.
company_details=Company.objects.all()
def login(request):
  context={
           "details":company_details,
                                
  }
  return render(request ,'customers/login.html', context)
def loader(request):
  context={
           "details":company_details,
                                
  }
  return render(request ,'customers/loader.html', context)
def home(request,id):
  customer=Customer.objects.get(id=id)

  emi=EMI.objects.all().filter(property_ref__cust_id=id)
  tx=Transaction.objects.all().filter(customer_ref=id)
  temp_bookings= TempBooking.objects.all().filter(customer_ref=id).order_by('id')
  bookings= Booking.objects.all().filter(customer_ref=id)
  form=CustomerForm(request.POST or None,instance=customer)
  if form.is_valid():
    form.save()
    form=CustomerForm(request.POST or None)
   
  context={
           "details":company_details,
           "form":form,
           "customer":customer,
           "emi":emi,
           "tx":tx, 
           "bookings":bookings,
           "temp_bookings":temp_bookings,        
               
  }
  return render(request ,'customers/home.html',context) 
  
def register(request):
  
  form=CustomerForm(request.POST or None)
  if form.is_valid():
    form.save()
    return redirect(reverse('customers:loader'))
  context={
           "details":company_details,
           "form":form          
               
  }
  return render(request ,'customers/registration.html',context)
  
  

associate/templates/associate/blank.html
{% extends "base.html" %}
{% block title %}

{% endblock title %}
<!-- heading  -->
{% block heading %}

{% endblock %}


<!-- desktop menu -->
{% block desk-sidebar%}
{% include 'sidebar.html' %}
{% endblock %}


<!-- Main Conent -->
{% block content %}
<div class="row ">
    <div class="col-lg-12">
        sdf
    </div>

</div>
{% endblock %}


{% load static %}

associate/templates/associate/customerView.html
{% extends "base.html" %}
<!-- title  -->
{% block title %}
Client View
{% endblock title %}
<!-- heading  -->
{% block heading %}
Client View
{% endblock %}


<!-- desktop menu -->
{% block desk-sidebar%}
{% include 'sidebar.html' %}
{% endblock %}

<!-- Main Conent -->
{% block content %}

{% if customer.associate_ref.id == associate.id %}

<div class="card">

  <div class="card-body">
    <table class="table ml-1 mr-1">
      <tbody>

        <tr>
          <th scope="row">Client ID</th>

          <td> {{customer.id}}</td>
        </tr>
        <tr>
          <th scope="row">Client Name</th>

          <td>{{customer.name}}</td>
        </tr>
        <tr>
          <th scope="row">Contact Number</th>
          <td>


            {% if customer.country_code %}
            {{customer.country_code}}-
            {% endif %}
            {{customer.contact_no}} </td>

          <!--  <td>{{customer.id}} </td>
         <td>{{customer.name}}</td>
         <td> 
           
          
          {% if customer.country_code %}
          {{customer.country_code}}-
          {% endif %}
            {{customer.contact_no}} </td>
           <td>
                {% if customer.country_code %}
                {{customer.country_code}}-
                {% endif %} {{customer.alternate_no}}
            </td> 
        
          -->
        <tr>
          <th scope="row">Altenate Contact number</th>

          <td>
            {% if customer.country_code %}
            {{customer.country_code}}-
            {% endif %} {{customer.alternate_no}}
          </td>
        </tr>
        <tr>
          <th scope="row">Email</th>


          <td>
            {{customer.email}}
          </td>
        </tr>
        <tr>
          <th scope="row">Date Of Joining</th>

          <td>
            {{customer.createdAt}}
          </td>
        </tr>


        <tr>
          <th scope="row">Total Amount to be paid</th>
          <td>
            <script>
              var cost = 0;
            </script>
            {% for property in properties %}
            {{item.serial_no}}
            {% load mathfilters %}
            {% load humanize %}
            {% with cost=property.section_id.cost_per_unit factor=property.price_rule.premium_price|add:100|div:100 %}

            <script>
              cost = parseInt("{{cost|mul:factor|mul:property.section_id.area}}") + cost;
            </script>

            {% endwith %}
            {% endfor %}
            &#8377;
            <script>


              document.write(cost)</script>

          </td>
        </tr>
        <tr>
          <th scope="row">Payment Summary</th>
          <td>
            <span class="text-success">
              Amount Paid: &#8377; {{amount.amount__sum}}
              <script>
                var amount = parseInt("{{amount.amount__sum}}");
              </script>
            </span><br>
            <span class="text-danger">
              Outstanding Amount: &#8377;
              <script>
                document.write(cost - amount);
              </script>
            </span>
          </td>
        </tr>



        <tr class="text-success">
          <th scope="row">Number of EMIs Paid</th>

          <td>{{paid_emi.emi__count}}</td>
        </tr>
        <tr class="text-danger">
          <th scope="row">Number of EMIs Pending</th>

          <td>{{pending_emi.emi__count}}</td>
        </tr>


      </tbody>
    </table>
  </div>
  <div class="card-body ">
    <ul class="nav nav-pills nav-pills-info" role="tablist">
      <li class="nav-item">
        <a class="nav-link active show" data-toggle="tab" href="#link1" role="tablist">
          Properties
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#link2" role="tablist">
          EMIs
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#link3" role="tablist">
          Payments
        </a>
      </li>
    </ul>
    <div class="tab-content tab-space">
      <div class="tab-pane active show" id="link1">
        <div class="p-2">
          <table class=" myTable flex-table table table-striped ">
            <thead>
              <tr>
                <th>Project Name</th>
                <th>Serial Number</th>

                <th>Status</th>
                <th>Paid EMIs</th>
                <th>Pending EMIs</th>
                <!-- <th>Actions</th> -->
              </tr>
            </thead>
            <tbody>
              {% load mathfilters %}

              {% for property in properties  %}

              <tr>
                <td>
                  <a href="{% url 'associate:project_view' id=property.section_id.project_ref.id %}" target="_blank"
                    rel="noopener noreferrer">
                    {{property.section_id.project_ref.project_name}}
                  </a>
                </td>
                <td>
                  <a href="{% url 'associate:section_view' id=property.section_id.id proid=property.section_id.project_ref.id %}"
                    target="_blank" rel="noopener noreferrer">
                    {{property.section_id.section_prefix}}-{{property.serial_no}}
                  </a>
                </td>

                <td>{% if property.status_code == "V"  %}
                  <span class="badge  badge-pill badge-success">Vacant</span>
                  {% elif property.status_code == "H" %}
                  <span class="badge badge-pill badge-warning">Hold</span>
                  {% elif property.status_code == "B" %}
                  <span class="badge badge-pill badge-danger">Booked</span>
                  {% elif property.status_code == "A" %}
                  <span class="badge badge-pill badge-primary">Alloted</span>
                  {% else  %}
                  <span class="badge badge-pill badge-secondary">Registered</span>

                  {% endif %}</td>
                <script>
                  var paid = 0;
                  var unpaid = 0;
                </script>
                {% for item in emi %}
                {% if item.property_ref.id == property.id %}
                {% if item.status %}
                <script>
                  paid++;
                </script>
                {% else %}
                <script>
                  unpaid++;
                </script>
                {% endif %}
                {% endif %}
                {% endfor %}

                <td>
                  <script>
                    document.write(paid);</script>
                </td>

                <td>
                  <script>
                    document.write(unpaid);
                  </script>
                </td>
                <!-- <td>a</td> -->
              </tr>
              {% endfor %}

            </tbody>
          </table>
          <script>
            $(document).ready(function () {
              $('.myTable').DataTable();
            });
          </script>
        </div>

      </div>
      <div class="tab-pane" id="link2">
        Efficiently unleash cross-media information without cross-media value. Quickly maximize timely deliverables for
        real-time schemas.
        <br>
        <br>Dramatically maintain clicks-and-mortar solutions without functional solutions.
      </div>
      <div class="tab-pane" id="link3">
        <table class=" myTable flex-table table table-striped ">
          <thead>
            <tr>
              <th>Transaction ID</th>
              <th>Payment Mode</th>

              <th>Date</th>
              <th>Reference no</th>
              <th>Amount</th>
              <th>Description</th>
              <!-- <th>Actions</th> -->
            </tr>
          </thead>
          <tbody>


            {% for tr in tx %}
            <tr>
              <td data-label="Transaction ID">{{tr.id}} </td>
              <td data-label="Payment Mode">

                {% if tr.pay_method == 'C' %}
                Cash
                {% elif tr.pay_method == 'D' %}
                Demand Draft
                {% elif tr.pay_method == 'N' %}
                NEFT
                {% elif  tr.pay_method == 'Q' %}
                Cheque
                {% endif %}

              </td>
              <td data-label="Date">{{tr.date}}</td>
              <td data-label="Reference No">{{tr.reference_no}}</td>
              <td data-label="Amount">{{tr.amount}} </td>
              <td data-label="Description">tr.description}} </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>

  {% else %}
  <span class="text-danger" style="font-weight: 500;
font-size: 20pt;">
    Sorry,this is not your Client!
  </span>
  <br>
  <span style="font-weight: 500;
font-size: 9pt;
color: black;
">For any discrepency please contact admin

  </span>

  {% endif %}
  {% endblock %}
  {% load static %}

associate/templates/associate/downlines.html
{% extends "base.html" %}
{% block title %}
My Downlines
{% endblock title %}
<!-- heading  -->
{% block heading %}
My Downlines
{% endblock %}


<!-- desktop menu -->
{% block desk-sidebar%}
{% include 'sidebar.html' %}
{% endblock %}


<!-- Main Conent -->
{% block content %}
<div class="row ">
    <div class="col-lg-12">
        <table id="example" class="display" style="width:100%">
                <thead>
                        <tr>
                          <th >AID</th>
                          <th>Name</th>
                          <th>Contact Number</th>
                         <!--  <th>Alternate Number</th> -->
                          <th>Email</th>
                          <th>Date of Joining</th>
                          <th>Listed Customers</th>
                          <th>Actions</th>
                        </tr>
                      </thead>
                      <tbody>
                        {% load mathfilters %}
                        {% for downline in associate_list %}
                        
                        {% if downline.id != associate.id %}
                
                        <tr>
                         <td>{{downline.id}} </td>
                         <td>{{downline.name}}</td>
                         <td> 
                           
                          
                          {% if downline.country_code %}
                          {{downline.country_code}}-
                          {% endif %}
                            {{downline.contact_no}} </td>
                            <!-- <td>
                                {% if customer.country_code %}
                                {{customer.country_code}}-
                                {% endif %} {{customer.alternate_no}}
                            </td> -->
                         
                          <td>
                            {{downline.email}}
                          </td>
                          <td>
                            {{downline.createdAt|date}}
                          </td>
                        <td>
                          
                       
                            <script> var count=0;</script>
                            {% for item in customers %}
                              
                              {% if item.associate_ref.id == downline.id%}
                                <script>count++;
                               </script>
                              {% endif %}
                               
                            {% endfor %}
                            <script>document.write(count);</script>
                
                           
                        </td>
                          <td>
                            <a class="btn btn-sm  btn-info"
                            href="{% url 'associate:downline_view' id=downline.id %}"
                            >
                              <i class="far fa-eye"></i> View
                            </a>
                        
                            
                          
                          </td>
                
                        </tr>
                        {% endif %}
                        {% endfor %}
                
                      </tbody>
            <tfoot>
                <tr>
                  <th >AID</th>
                  <th>Name</th>
                  <th>Contact Number</th>
                 <!--  <th>Alternate Number</th> -->
                  <th>Email</th>
                  <th>Date of Joining</th>
                  <th>Listed Customers</th>
                  <th>Actions</th>
                </tr>
            </tfoot>
        </table>
    </div>

</div>
<script>
$(document).ready(function() {
    $('#example').DataTable( {
        "pagingType": "full_numbers"
    } );
} );
</script>
{% endblock %}


{% load static %}

associate/templates/associate/earningsForcast.html
{% extends "base.html" %}
{% block title %}
Earnings Forcast
{% endblock title %}
<!-- heading  -->
{% block heading %}
Earnings Forcast
{% endblock %}

<!-- desktop menu -->
{% block desk-sidebar%}
{% include 'sidebar.html' %}
{% endblock %}


<!-- Main Conent -->
{% block content %}


{% endblock %}

associate/templates/associate/leaderRewards.html
{% extends "base.html" %}
{% block title %}
Leader Rewards
{% endblock title %}
<!-- heading  -->
{% block heading %}
Leader Rewards
{% endblock %}


<!-- desktop menu -->
{% block desk-sidebar%}
{% include 'sidebar.html' %}
{% endblock %}


<!-- Main Conent -->
{% block content %}
<div class="row ">
    <div class="col-lg-12">
        sdf
    </div>

</div>
{% endblock %}


{% load static %}

associate/templates/associate/myEarnings.html
{% extends "base.html" %}
{% block title %}
My Earnings
{% endblock title %}
<!-- heading  -->
{% block heading %}
My Earnings
{% endblock %}

<!-- desktop menu -->
{% block desk-sidebar%}
{% include 'sidebar.html' %}
{% endblock %}


<!-- Main Conent -->
{% block content %}
{{year}}

{% endblock %}