associate/urls.py
from django.urls import path,include
from . import views

app_name="associate"
urlpatterns = [  
    path('', views.index,name='home'),
   # path('register', views.register, name='register'),
    path('project', views.projects,name='projects'),
    path('project/<int:id>/', views.projectView, name='project_view'),
    path('project/<int:proid>/section/<int:id>', views.sectionView, name='section_view'), 
    path('property/<int:id>/', views.propertyView,name='property_view'),  
    path('customers', views.customerListView, name='customers'),
    path('customers/<int:id>/', views.customerView, name='customer_view'),
    path('rewards', views.rewardView, name='rewards'),
    path('upline', views.uplineView, name='upline'), 
    path('downlines', views.downlines, name='downlines'),
    path('downlines/<int:id>', views.downlineView, name='downline_view'),   
    path('buisness-summary', views.buisnessSummary, name='buisness_summary'),
    path('team-buisness', views.teamBuisness, name='team_buisness'),
    path('leader-rewards', views.leaderRewards, name='leader_rewards'),
    path('my-earnings', views.myEarnings, name='my_earnings'),
    path('earnings-forcast', views.earningForcast, name='earning_forcast'),
    path('passbook', views.passbook, name='passbook'),
    path('profile', views.myProfile, name='profile'),
    path('profile/edit', views.profileEdit, name='profile_edit'), 
    path('changepwd', views.changePwd, name='changepwd'),              
    ]

    #project/id/edit
    

realEstate/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings 
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('webapp.urls')),
    path('associate/' , include('associate.urls')),
    path('customers/' , include('customers.urls')),
    path('owner/' , include('owner.urls')),
    path('projects/' , include('projects.urls')),
    path('api/customer/' , include('customers.api.urls')),
    path('api/project/' , include('projects.api.urls')),
    path('user/' , include('user.urls'))
    #path('report/' , include('reports.urls'))
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path,include
from . import views

app_name="user"
urlpatterns = [  
    
    path('login', views.login ,name='login'),
   # path('register', views.register ,name='register'),
   # path('forgot-password', views.forgotPassword ,name='forgot'),
    path('logout', views.logout ,name='logout'),
     
    ]

    #project/id/edit
    

realEstate/templates/sidebar.html
{% if associate %}
<div class="user">
  {% load static %}
  <div class="photo">
    <img src="{% get_media_prefix %}{{associate.photo}} " />
  </div>
  <div class="user-info">
    <a data-toggle="collapse" href="#collapseExample" class="username">
      <span>
        {{associate.name}}
        <b class="caret"></b>
      </span>
    </a>
    <div class="collapse" id="collapseExample">
      <ul class="nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'associate:profile' %}">
            <span class="sidebar-mini"> MP </span>
            <span class="sidebar-normal"> My Profile </span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'associate:profile_edit' %}">
            <span class="sidebar-mini"><i class="far fa-edit"></i></span>
            <span class="sidebar-normal">Edit Profile </span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'associate:changepwd' %}">
            <span class="sidebar-mini">
              <div class="material-icons">settings</div>
            </span>
            <span class="sidebar-normal"> Settings </span>
          </a>
        </li>
        <!-- <li class="nav-item">
                     <a class="nav-link">
                        <span class="sidebar-mini"> <div class="material-icons">settings_power</div></i> </span>
                        <form action="{% url 'user:logout' %}" method="post">
                        <button type="submit" class="btn btn-danger"> Logout </button>
                      </form>
                    </a>
                </li> -->
        <li class="nav-item">
          <div class="nav-link ml-4">
            <form action="{% url 'user:logout' %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn btn-danger btn-sm">
                <!-- <i class="material-icons" style="font-size: 16pt;">
                                 settings_power</i> -->
                <div class="material-icons">settings_power</div> Logout
              </button>
            </form>
          </div>
        </li>
      </ul>
    </div>
  </div>
</div>
{% endif %}



<ul class="nav">

  {% for item in menu %}
  {% if item.sub|length < 1 %}
  <li class="nav-item {{item.active}} ">
    <a class="nav-link" href="{{item.url}} ">
      <i class="fa {{item.icon}}"></i>
      <p> {{item.name}}</p>
    </a>
  </li>
  {% else %}
  <li class="nav-item {{item.active}}">
    <a class="nav-link" data-toggle="collapse" href="#{{item.id}}">
      <i class="fa {{item.icon}}"></i>
      <p> {{item.name}}
        <b class="caret"></b>
      </p>
    </a>
    <div class="collapse" id="{{item.id}}">
      <ul class="nav">

        {% for subitem in item.sub %}
        <li class="nav-item ">
          <a class="nav-link" href="{{subitem.url}}">
            <span class="sidebar-mini"> * </span>
            <span class="sidebar-normal"> {{subitem.name}}</span>
          </a>
        </li>
        {% endfor %}
      </ul>
    </div>
  </li>

  {% endif %}
  {% endfor %}
</ul>

realEstate/templates/temp2.html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Admin panel">
    <meta name="author" content="Codinfy">
    <meta name="keywords" content="codinfy, codinfy, IT,software">

    <!-- Title Page-->
    
    {% load static %}
    <title> 
         {% block title %}
        {% endblock title %} 
    </title>
    <!-- Fontfaces CSS-->
   <!--  <link href="{% static "css/font-face.css" %}" rel="stylesheet" media="all"> -->
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet"> 
    <link href="https://unpkg.com/ionicons@4.5.5/dist/css/ionicons.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
<!--     <link href="{% static "vendor/font-awesome-4.7/css/font-awesome.min.css" %}" rel="stylesheet" media="all"> -->
    <link href="{% static "vendor/font-awesome-5/css/fontawesome-all.min.css" %}" rel="stylesheet" media="all">
    <link href="{% static "vendor/mdi-font/css/material-design-iconic-font.min.css" %}" rel="stylesheet" media="all">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
    <!-- Bootstrap CSS-->
  <!--   <link href="{% static "vendor/bootstrap-4.1/bootstrap.min.css" %}" rel="stylesheet" media="all">
    --> <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" >
    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    
    <!-- Vendor CSS-->
  <!--   <link href="{% static "vendor/animsition/animsition.min.css" %}" rel="stylesheet" media="all"> -->
    <link href="{% static "vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css" %}" rel="stylesheet" media="all">
    <link href="{% static "vendor/wow/animate.css" %}" rel="stylesheet" media="all">
    <link href="{% static "vendor/css-hamburgers/hamburgers.min.css" %}" rel="stylesheet" media="all">
    <link href="{% static "vendor/slick/slick.css" %}" rel="stylesheet" media="all">
    <link href="{% static "vendor/select2/select2.min.css" %}" rel="stylesheet" media="all">
    <link href="{% static "vendor/perfect-scrollbar/perfect-scrollbar.css" %}" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="{% static "css/theme.css" %}" rel="stylesheet" media="all">

</head>
    {% block body%}
    {% endblock body %}

    <!-- Jquery JS-->
    <script src="{% static "vendor/jquery-3.2.1.min.js" %}"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <!-- Bootstrap JS-->
    <script src="{% static "vendor/bootstrap-4.1/popper.min.js" %}"></script>
    <script src="{% static "vendor/bootstrap-4.1/bootstrap.min.js" %}"></script>
    <!-- Vendor JS       -->
    <script src="{% static "vendor/slick/slick.min.js" %}">
    </script>
    <script src="{% static "vendor/wow/wow.min.js" %}"></script>
    <!-- <script src="{% static "vendor/animsition/animsition.min.js" %}"></script> -->
    <script src="{% static "vendor/bootstrap-progressbar/bootstrap-progressbar.min.js" %}">
    </script>
    <script src="{% static "vendor/counter-up/jquery.waypoints.min.js" %}"></script>
    <script src="{% static "vendor/counter-up/jquery.counterup.min.js" %}">
    </script>
    <script src="{% static "vendor/circle-progress/circle-progress.min.js" %}"></script>
    <script src="{% static "vendor/perfect-scrollbar/perfect-scrollbar.js" %}"></script>
    <script src="{% static "vendor/chartjs/Chart.bundle.min.js" %}"></script>
    <script src="{% static "vendor/select2/select2.min.js" %}">
    </script>

    <!-- Main JS-->
    <script src="{% static "js/main.js" %}"></script>
</html>
<!-- end document-->

realEstate/templates/wireframe.html
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags-->
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Admin panel">
  <meta name="author" content="Codinfy">
  <meta name="keywords" content="codinfy, codinfy, IT,software">

  <!-- Title Page-->

  {% load static %}
  <!-- Fontfaces CSS-->
  <link rel="icon" type="image/png" href="{% get_media_prefix %}/images/config/logo.png"/>
  <link href="https://unpkg.com/ionicons@4.5.5/dist/css/ionicons.min.css" rel="stylesheet">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"
    integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css"
    href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="//cdn.jsdelivr.net/chartist.js/latest/chartist.min.css">

  <!-- Bootstrap  -->
  <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
  
  <!-- material dashboard css -->
  
  <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
  <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.bootstrap4.min.css">
  <link href="{% static "css/material-dashboard.min.css" %}" rel="stylesheet" media="all">
  <link href="{% static "css/flex-table.css" %}" rel="stylesheet" media="all">
  
<script src="//cdn.jsdelivr.net/chartist.js/latest/chartist.min.js"></script>

  

  <title>
    {% block title %}
    {% endblock title %}
  </title>

  {% block body%}
  {% endblock body %}

  <!--   Core JS Files   -->
 
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="{% static "js/plugin/bootstrap-material-design.min.js" %}"></script>
  <script src="{% static "js/plugin/perfect-scrollbar.jquery.min.js" %}"></script>
<!-- datatables -->
  <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
  <!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="{% static "js/material-dashboard.min.js" %}"></script>
  <script src="{% static "js/plugin/uniform.jquery.js" %}"></script>
  <!-- jasny-fileupload  -->
  <script src="{% static "js/plugin/jasny-fileupload.min.js" %}"></script>
  <!--  Plugin for Sweet Alert  -->
  <script src="{% static "js/plugin/sweetalert2.js" %}"></script>
    <!--  Plugin for bootstrap NOtify  -->
  <script src="{% static "js/plugin/bootstrap-notify.js" %}"></script>
  <!-- Sharrre libray    -->
  <!--  https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js
https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js
https://cdn.datatables.net/responsive/2.2.3/js/responsive.bootstrap4.min.js -->
<script src="//cdn.jsdelivr.net/chartist.js/latest/chartist.min.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.3/js/responsive.bootstrap4.min.js"></script>

  <!--   <script src="{% static "js/plugin/sharre.js" %}"></script> -->

  <script src="{% static "js/home.js" %}"></script>


</html>
<!-- end document-->